"""macOS clipboard watching: the general pasteboard's change count, polled.

The pasteboard offers no change notification, so this polls `changeCount` (a cheap
integer) twice a second, which is what other clipboard managers on macOS do. Content
that a password manager marks as concealed or transient is never read.
"""

from __future__ import annotations

import contextlib
import time
from collections.abc import Callable
from contextlib import AbstractContextManager
from dataclasses import replace
from importlib import import_module
from typing import Any

import clipstore
from clipwatch import Clip, Unavailable, limit_clip

TEXT_TYPE = "public.utf8-plain-text"
PNG_TYPE = "public.png"
TIFF_TYPE = "public.tiff"
# nspasteboard.org conventions used by password managers and other apps.
CONCEALED_TYPES = frozenset(
    {
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    }
)
TIFF_FACTOR = 4  # A TIFF is far larger than the PNG made from it; cap the raw size.


class MacWatcher:
    def __init__(
        self,
        pasteboard: Any,
        to_png: Callable[[bytes], bytes],
        *,
        pool: Callable[[], AbstractContextManager[Any]] = contextlib.nullcontext,
        poll: float = 0.5,
        frontmost: Callable[[], str] = lambda: "",
        clock: Callable[[], float] = time.monotonic,
        sleep: Callable[[float], None] = time.sleep,
        max_text: int = clipstore.MAX_TEXT_BYTES,
        max_image: int = clipstore.MAX_IMAGE_BYTES,
    ) -> None:
        self._pasteboard = pasteboard
        self._to_png = to_png
        self._pool = pool
        self._frontmost = frontmost  # Bundle id of the app in front: the likely copier.
        self._poll = poll
        self._clock = clock
        self._sleep = sleep
        self._max_text = max_text
        self._max_image = max_image
        # What is on the clipboard now was copied before capture began: not ours to keep.
        self._last = pasteboard.changeCount()

    def next_change(self, timeout: float) -> Clip | None:
        deadline = self._clock() + max(0.0, timeout)
        while True:
            with self._pool():  # Releases Cocoa objects on every pass of this long loop.
                current = self._pasteboard.changeCount()
                if current != self._last:
                    self._last = current
                    return limit_clip(self._read(), self._max_text, self._max_image)
            remaining = deadline - self._clock()
            if remaining <= 0:
                return None
            self._sleep(min(self._poll, remaining))

    def _read(self) -> Clip:
        clip = self._read_content()
        try:
            source = self._frontmost()
        except Exception:  # noqa: BLE001 - not knowing the app must never lose the copy
            source = ""
        return replace(clip, source_app=source) if source else clip

    def _read_content(self) -> Clip:
        board = self._pasteboard
        types = {str(kind) for kind in (board.types() or [])}
        if types & CONCEALED_TYPES:
            return Clip(concealed=True)
        if TEXT_TYPE in types:
            text = board.stringForType_(TEXT_TYPE)
            if text and text.strip() and len(text.encode("utf-8", "replace")) <= self._max_text:
                return Clip(text=str(text))
        if PNG_TYPE in types:
            data = board.dataForType_(PNG_TYPE)
            if data is not None and len(data) <= self._max_image:
                return Clip(image_png=bytes(data))
        if TIFF_TYPE in types:
            data = board.dataForType_(TIFF_TYPE)
            if data is not None and len(data) <= TIFF_FACTOR * self._max_image:
                png = self._to_png(bytes(data))
                if png:
                    return Clip(image_png=png)
        return Clip()

    def close(self) -> None:
        """Nothing to release: the pasteboard is only polled."""


def tiff_to_png(tiff: bytes) -> bytes:
    """PNG bytes for TIFF image data, or nothing if it cannot be decoded."""
    appkit = import_module("AppKit")
    foundation = import_module("Foundation")
    data = foundation.NSData.dataWithBytes_length_(tiff, len(tiff))
    representation = appkit.NSBitmapImageRep.imageRepWithData_(data)
    if representation is None:
        return b""
    png = representation.representationUsingType_properties_(appkit.NSBitmapImageFileTypePNG, {})
    return bytes(png) if png is not None else b""


def frontmost_bundle() -> str:
    """The bundle id of the frontmost application, or "" when unknown."""
    try:
        appkit = import_module("AppKit")
        app = appkit.NSWorkspace.sharedWorkspace().frontmostApplication()
        return str(app.bundleIdentifier() or "") if app is not None else ""
    except Exception:  # noqa: BLE001
        return ""


def create() -> MacWatcher:
    try:
        appkit = import_module("AppKit")
        objc = import_module("objc")
    except ImportError as exc:
        raise Unavailable(
            "Clipboard history needs PyObjC in the app's private environment."
        ) from exc
    return MacWatcher(
        appkit.NSPasteboard.generalPasteboard(),
        tiff_to_png,
        pool=objc.autorelease_pool,
        frontmost=frontmost_bundle,
    )
