"""Build the Clipboard+ window theme from the sv-ttk "Sun Valley" light theme.

sv-ttk (MIT, https://github.com/rdbende/Sun-Valley-ttk-theme) draws modern, rounded
widgets from a sprite sheet. Clipboard+ is amber, not blue, so this recolors that sheet
and adds a red "danger" button, then writes two files next to the app's icons:

    lib/clipboardplus-theme.tcl   the theme (sprites and styles merged, one file)
    lib/clipboardplus-theme.png   the recolored sprite sheet

The output is committed so no runtime dependency is needed; rerun this only to change
the theme:  pip install sv-ttk==2.6.1 pillow && python tools/build_theme.py
"""

from __future__ import annotations

import colorsys
import re
import sys
from pathlib import Path

import sv_ttk  # type: ignore[import-not-found]
from PIL import Image, ImageDraw

LIB = Path(__file__).resolve().parents[1] / "lib"
SOURCE = Path(sv_ttk.__file__).parent / "theme"
BLUE = (190, 245)  # Degrees of hue that belong to sv-ttk's accent blue.
AMBER, RED = 26, 4  # Clipboard+'s accent (#b45309) and its danger color.
ACCENT, ACCENT_TEXT = "#b45309", "#f6dcc0"
SELECTION = "#b45309"
SURFACE, BORDER = "#ffffff", "#e2e8f0"  # Keep in step with app_styles.py.
DANGER_SPRITES = ("rest", "hover", "pressed", "dis", "focus", "focus-hover")
HEADER = """\
# Clipboard+ window theme, generated by tools/build_theme.py. Do not edit by hand.
#
# Derived from the Sun Valley ttk theme, MIT License, Copyright (c) rdbende
# (https://github.com/rdbende/Sun-Valley-ttk-theme), recolored to Clipboard+'s amber.
# See THIRD-PARTY-NOTICES.md.

"""


def recolor(image: Image.Image, region: tuple[int, int, int, int], hue: int) -> Image.Image:
    """The pixels of `region` with sv-ttk's blue turned into `hue`, shade and alpha kept."""
    piece = image.crop(region)
    data = bytearray(piece.tobytes())
    for index in range(0, len(data), 4):
        h, s, v = colorsys.rgb_to_hsv(
            data[index] / 255, data[index + 1] / 255, data[index + 2] / 255
        )
        if s > 0.15 and BLUE[0] <= h * 360 <= BLUE[1]:
            data[index : index + 3] = bytes(
                round(c * 255) for c in colorsys.hsv_to_rgb(hue / 360, s, v)
            )
    return Image.frombytes("RGBA", piece.size, bytes(data))


def main() -> int:
    sheet = Image.open(SOURCE / "spritesheet_light.png").convert("RGBA")
    sprites = (SOURCE / "sprites_light.tcl").read_text(encoding="utf-8")
    theme = (SOURCE / "light.tcl").read_text(encoding="utf-8")

    boxes = {
        name: (int(x), int(y), int(x) + int(w), int(y) + int(h))
        for name, x, y, w, h in re.findall(r"^\s+(\S+) (\d+) (\d+) (\d+) (\d+) \\$", sprites, re.M)
    }
    recolored = sheet.copy()
    for box in boxes.values():
        recolored.paste(recolor(sheet, box, AMBER), box[:2])

    # The card: white with a hairline border and rounded corners, drawn large and shrunk
    # for smooth edges. Frames in the "Panel.TFrame" style use it.
    scale, size = 6, boxes["card"][2] - boxes["card"][0]
    card = Image.new("RGBA", (size * scale, size * scale), (0, 0, 0, 0))
    ImageDraw.Draw(card).rounded_rectangle(
        (0, 0, size * scale - 1, size * scale - 1),
        radius=9 * scale,
        fill=SURFACE,
        outline=BORDER,
        width=scale,
    )
    recolored.paste(card.resize((size, size), Image.Resampling.LANCZOS), boxes["card"][:2])

    # Red copies of the accent button, in a new strip under the sheet.
    strip_y = sheet.height
    recolored = recolored.crop((0, 0, sheet.width, strip_y + 20))
    extra = ""
    for index, state in enumerate(DANGER_SPRITES):
        source = boxes[f"button-accent-{state}"]
        recolored.paste(recolor(sheet, source, RED), (index * 20, strip_y))
        extra += f"  button-danger-{state} {index * 20} {strip_y} 20 20 \\\n"
    sprites = sprites.rstrip().removesuffix("]") + extra + "]\n"
    recolored.save(LIB / "clipboardplus-theme.png", optimize=True)

    theme = theme.replace("source [file join [file dirname [info script]] sprites_light.tcl]", "")
    theme = theme.replace("spritesheet_light.png", "clipboardplus-theme.png")
    theme = theme.replace("sun-valley-light", "clipboardplus").replace("sv_light", "clipboardplus")
    theme = re.sub(r"\n\s*package provide [^\n]*", "", theme)
    theme = theme.replace('"#2f60d8"', f'"{SELECTION}"').replace('"#005fb8"', f'"{ACCENT}"')
    theme = theme.replace('"#c1d8ee"', f'"{ACCENT_TEXT}"')
    theme = theme.replace("Card.TFrame", "Panel.TFrame")
    # Scrollbars are a slim thumb on a trough: the arrow buttons at the ends are dropped.
    theme = re.sub(r"\n\s*(?:Vertical|Horizontal)\.Scrollbar\.\w+arrow -side \w+", "", theme)

    danger = """
    # Danger.TButton
    ttk::style layout Danger.TButton {
      DangerButton.button -children {
        DangerButton.padding -children {
          DangerButton.label -side left -expand 1
        }
      }
    }

    ttk::style configure Danger.TButton -padding {8 2 8 3} -anchor center -foreground "#ffffff"
    ttk::style map Danger.TButton -foreground [list pressed "#f6d0cb" disabled "#ffffff"]

    ttk::style element create DangerButton.button image \\
      [list $I(button-danger-rest) \\
        disabled $I(button-danger-dis) \\
        pressed $I(button-danger-pressed) \\
        {active focus} $I(button-danger-focus-hover) \\
        active $I(button-danger-hover) \\
        focus $I(button-danger-focus) \\
      ] -border 4 -sticky nsew

    # Menubutton
"""
    theme = theme.replace("\n    # Menubutton\n", danger, 1)
    colors = """
proc configure_colors {} {
  if {[ttk::style theme use] != "clipboardplus"} {
    return
  }
  ttk::style configure . \\
    -background $ttk::theme::clipboardplus::colors(-bg) \\
    -foreground $ttk::theme::clipboardplus::colors(-fg) \\
    -troughcolor $ttk::theme::clipboardplus::colors(-bg) \\
    -focuscolor $ttk::theme::clipboardplus::colors(-selbg) \\
    -selectbackground $ttk::theme::clipboardplus::colors(-selbg) \\
    -selectforeground $ttk::theme::clipboardplus::colors(-selfg) \\
    -insertwidth 1 \\
    -insertcolor $ttk::theme::clipboardplus::colors(-fg) \\
    -fieldbackground $ttk::theme::clipboardplus::colors(-bg) \\
    -borderwidth 0 \\
    -relief flat
  ttk::style map . -foreground [list disabled $ttk::theme::clipboardplus::colors(-disfg)]
}

bind [winfo class .] <<ThemeChanged>> {+configure_colors}
"""
    output = HEADER + "package require Tk 8.6-\n\n" + sprites + theme + colors
    (LIB / "clipboardplus-theme.tcl").write_text(output, encoding="utf-8")
    print(f"wrote {LIB / 'clipboardplus-theme.tcl'} and {LIB / 'clipboardplus-theme.png'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
